### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by CloudeLecaw** [dvargas135/eZProtector#12]
This Error happens on plugin loading if u set all Setting to TRUE in the config.
maybe ist a known issues and u know what causes it..
Protocollib 4.1 for Spigot 1.10.2 Build 318 (lastest download there), Spigot 1.10.2, ezProtector 4.0.2

[08:57:38] [Server thread/INFO]: [eZProtector] Enabling eZProtector v4.0.2
[08:57:38] [Server thread/INFO]: [eZProtector] Reloading config...
[08:57:38] [Server thread/ERROR]: Error occurred while enabling eZProtector v4.0.2 (Is it up to date?)
java.lang.NullPointerException
	at ez.plugins.dan.Main.onEnable(Main.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[08:57:39] [Server thread/INFO]: Done (5,665s)! For help, type "help" or "?"
[08:57:40] [Craft Scheduler Thread - 0/INFO]: Checking update...
[08:57:40] [Craft Scheduler Thread - 0/INFO]: eZProtector is up to date.

**Comment by dvargas135** [comment]
Plugin updated, please update.
