### ISSUE TITLE
Could not load 'plugins/eZProtector.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Magino0088** [dvargas135/eZProtector#36]
Spigot: 1.11.2
Plugins: 0

org.bukkit.plugin.UnknownDependencyException: ProtocolLib
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.11.2.jar:git-Spigot-625bc00-b5f7b6d]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot-1.11.2.jar:git-Spigot-625bc00-b5f7b6d]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.2.jar:git-Spigot-625bc00-b5f7b6d]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-625bc00-b5f7b6d]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Magino0088** [comment]
Spigot: 1.11.2
Plugins: 0

**Comment by GiansCode** [comment]
org.bukkit.plugin.UnknownDependencyException: ProtocolLib

Install ProtocolLib

**Comment by Magino0088** [comment]
I have but also if I now block WDL comes always only separated when a player comes in and he does not see the warning.


UUID of player Magino is 24kdl42jf9-ef17-40fb-b554-abc18hdjgf5fd
Magino[/293.885.904.61:35648] logged in with entity id 1 at ([worlds1]238.5399547307894, 72.0, 193.12202620912032)
Magino lost connection: �4The World Downloader Mod is not allowed.
Magino left the game
Kicked Prymo from the game: '�4The World Downloader Mod is not allowed.'
[WDLCompanion] Player Prymo has WDL installed.
[WDLCompanion] They are located in world world, at 238.58557646647894, 72.0, 193.12202620912032.
[WDLCompanion] They are running WDL version {"X-RTFM":"http://wiki.vg/Plugin_channels/World_downloader","X-UpdateNote":"The plugin message system will be changing shortly. Please stay tuned.","Version":"4.0.0.3","State":"Init?"}.

WARN
04.04.2017 17:36:07
17:36:07
handleDisconnection() called twice
