### ISSUE TITLE
Error on starting of: 4.0.1

### ISSUE THREAD

**Issue by CloudeLecaw** [dvargas135/eZProtector#4]
[14:55:11] [Server thread/ERROR]: Error occurred while enabling eZProtector v4.0.1 (Is it up to date?)
java.lang.NullPointerException
	at ez.plugins.dan.Main.onEnable(Main.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by dvargas135** [comment]
Hello, please send the complete log for further help.

**Comment by dvargas135** [comment]
Please update. If this error persists please open a new issue and provide the complete log.
