### ISSUE TITLE
Spigot updater

### ISSUE THREAD

**Issue by hoffarthaustin** [dvargas135/eZProtector#47]
[12:55:00 WARN]: [eZProtector] Plugin eZProtector v4.1.6 generated an exception
while executing task 46
java.lang.NullPointerException: null
        at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102
) ~[?:?]
        at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:
80) ~[?:?]
        at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.
java:39) ~[?:?]
        at ez.plugins.dan.Main$1.run(Main.java:58) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot.jar:git-Spigot-596221b-2c5c611]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot.jar:git-Spigot-596221b-2c5c611]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by CloudeLecaw** [comment]
Simply disable Metrics Update in the config
updater: false

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.
