### ISSUE TITLE
Generated an exception

### ISSUE THREAD

**Issue by RainOfPain125** [dvargas135/eZProtector#60]
[22:50:15 WARN]: [eZProtector] Plugin eZProtector v4.1.6 generated an exception while executing task 57
java.lang.NullPointerException: null
        at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102) ~[?:?]
        at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80) ~[?:?]
        at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39) ~[?:?]
        at ez.plugins.dan.Main$1.run(Main.java:58) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1320]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1320]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1320]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

Version: 4.1.6

 Plugins (68): ActionAnnouncer, AdvancedBan, AreaShop, ArrowTrails, Auctions, Autorank, AutoRestart, BlowableObsidians, BuycraftX, CFD, Chairs, ChatFeelings, ChatItem, ChestRestock, Citizens, ColoredAnvils, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, CrazyEnvoy, DailyBonus, DeluxeJoin, DiscordSRV, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, HolographicDisplays, InfoBook, InventoryFull, LimitCrafting, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, MobArena, Multiverse-Core, NoCheatPlus, NoPlugins, OldCombatMechanics, Orebfuscator4, PerWorldInventory, PlayerHeads, PluginLibrary, ProtocolLib, ServerListPlus, ShopGUIPlus, ShulkerBlock, SilkSpawners, SilkSpawnersShopAddon, SimpleBackup, SuperbVote, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, Vault, Votifier, Wild, WorldBorder, WorldEdit, WorldGuard

**Comment by bc-hill** [comment]
Set this, in your config:
updater: false

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.

**Comment by CloudeLecaw** [comment]
We are on version 4.2.5 allready. So pls update :-)
hm i beging to think  that may many owners never noticed DoNotPSamPls have  turned over this Project and turns on this great Little masterpeace 🥉
