### ISSUE TITLE
Generated an exception

### ISSUE THREAD

**Issue by Ant4rez** [dvargas135/eZProtector#61]
`[eZProtector] Plugin eZProtector v4.1.6 generated an exception while executing task 262 13.02 02:02:40 [Server] INFO java.lang.NullPointerException: null 13.02 02:02:40 [Server] INFO at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102) ~[?:?] 13.02 02:02:40 [Server] INFO at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80) ~[?:?] 13.02 02:02:40 [Server] INFO at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39) ~[?:?] 13.02 02:02:40 [Server] INFO at ez.plugins.dan.Main$1.run(Main.java:58) ~[?:?] 13.02 02:02:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4bd94dc-015bda4] 13.02 02:02:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-4bd94dc-015bda4] 13.02 02:02:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152] 13.02 02:02:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152] 13.02 02:02:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Comment by bc-hill** [comment]
Set this, in your config:
updater: false

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.

**Comment by CloudeLecaw** [comment]
we are on Version 4.2.5
