### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MikhailY** [dvargas135/eZProtector#62]
Latest Version

[07:38:23] [Craft Scheduler Thread - 1/WARN]: [eZProtector] Plugin eZProtector v4.1.6 generated an exception while executing task 19
java.lang.NullPointerException: null
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102) ~[?:?]
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80) ~[?:?]
	at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39) ~[?:?]
	at ez.plugins.dan.Main$1.run(Main.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit.jar:git-Paper-1326]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit.jar:git-Paper-1326]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [craftbukkit.jar:git-Paper-1326]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by bc-hill** [comment]
Set this, in your config:
updater: false

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.

**Comment by CloudeLecaw** [comment]
We are on version 4.2.5 allready. So pls update :-)
