### ISSUE TITLE
Task 76 Error.

### ISSUE THREAD

**Issue by TheIntelloBox** [dvargas135/eZProtector#63]
[18:19:00] [Craft Scheduler Thread - 13/WARN]: [eZProtector] Plugin eZProtector v4.1.6 generated an exception while executing task 76
java.lang.NullPointerException: null
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102) ~[eZProtector%20(2).jar:?]
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80) ~[eZProtector%20(2).jar:?]
	at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39) ~[eZProtector%20(2).jar:?]
	at ez.plugins.dan.Main$1.run(Main.java:58) ~[eZProtector%20(2).jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1329]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1329]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.

**Comment by CloudeLecaw** [comment]
hm i beging to Thing many ppls never noticed you have  turned on this Project :3
