### ISSUE TITLE
EzProtector Problem With PaperSpigot

### ISSUE THREAD

**Issue by AntoLuMeju99** [dvargas135/eZProtector#64]
Hi i got the latest version of EzProtector, but with paperspigot i got this error:

[23:13:28 WARN]: Exception in thread "Craft Scheduler Thread - 10"
[23:13:28 WARN]: org.apache.commons.lang.UnhandledException: Plugin eZProtector v4.1.5 generated an exception while executing task 25
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102)
        at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80)
        at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39)
        at ez.plugins.dan.Main$1.run(Main.java:79)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more

**Comment by bc-hill** [comment]
Set this, in your config:
updater: false

**Comment by AntoLuMeju99** [comment]
Did it, now no error, but if i type /pl eZProtector is red

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.

**Comment by CloudeLecaw** [comment]
We are on version 4.2.5 allready. So pls update :-)
