### ISSUE TITLE
eZProtector generated an exception while executing task 

### ISSUE THREAD

**Issue by Medialo** [dvargas135/eZProtector#66]
Good morning. Hello,
since a certain I noticed in the console that Ezprotect generate exceptions like this one, but I don't know why. Thank you for you help.

```
[eZProtector] Plugin eZProtector v4.1.6 generated an exception while executing task 63428
java.lang.NullPointerException: null
at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102) ~[?:?]
at ez.plugins.dan.SpigotUpdater.SpigotUpdater.‹init›(SpigotUpdater.java:80) ~[?:?]
at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39) ~[?:?]
at ez.plugins.dan.Main$1.run(Main.java:58) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[gbinvl_minecraft_spigot_1_12_2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [gbinvl_minecraft_spigot_1_12_2.jar:git-Spigot-7754231-94b0980]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by bc-hill** [comment]
Set this, in your config:
updater: false

**Comment by Medialo** [comment]
Was the problem that simple to solve? Okay, thank you so much! Sorry for the inconvenience.

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.
