### ISSUE TITLE
plugin don't want to run on 1.12.2 

### ISSUE THREAD

**Issue by FruTexR** [dvargas135/eZProtector#67]
[eZProtector] Plugin eZProtector v4.1.6 generated an exception while executing task 20
java.lang.NullPointerException: null
at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102) ~[?:?]
at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80) ~[?:?]
at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39) ~[?:?]
at ez.plugins.dan.Main$1.run(Main.java:58) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-3d850ec-809c399]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by DoNotSpamPls** [comment]
That was an issue with the updater that has since been fixed in the new version of eZProtector, you should update if you haven't already.

**Comment by CloudeLecaw** [comment]
We are on version 4.2.5 allready. So pls update :-)
