### ISSUE TITLE
Plugin doesn't load 

### ISSUE THREAD

**Issue by Assassin18** [dvargas135/eZProtector#68]
When i load this plugin on my server it couldn't load it and gives me this error : 

[16:20:50] [Server thread/INFO]: [eZProtector] Your server is running version v1_8_R1
[16:20:50] [Server thread/ERROR]: Could not load 'plugins/eZProtector.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:290) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
at ez.plugins.dan.Extras.Setup.setupEZP(Setup.java:49) ~[?:?]
at ez.plugins.dan.Main.(Main.java:28) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_141]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_141]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_141]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_141]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_141]
at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:76) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
at ez.plugins.dan.Extras.Setup.setupEZP(Setup.java:49) ~[?:?]
at ez.plugins.dan.Main.(Main.java:28) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_141]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_141]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_141]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_141]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_141]
at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:76) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
... 6 more

Im using spigot 1.8 and protoclib 1.8

**Comment by DoNotSpamPls** [comment]
You are using Spigot 1.8.0, which was not supported by eZProtector when you were reporting this issue. However, the new version of eZProtector supports it and you should update :)

**Comment by CloudeLecaw** [comment]
u Need to use Minimum of 1.8.8

**Comment by DoNotSpamPls** [comment]
@CloudeLecaw please stop talking bullsh*t to the plugin users, the plugin works on all 1.7-1.12 versions, maybe even earlier. I haven't forgotten to update it, that's the current position.

**Comment by CloudeLecaw** [comment]
fact is still ht was using version 4.1.6 and this was was needing a very high version of spigot
fpr the lowers it was only working in 4.1.5

here forgot to wrote what version he was using so i just could thing about the errormeassge and say he may used the 4.1.6..

but good to know u made it back compatible for all versions ;)
